In [3]:
# 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64


In [6]:
# 2. Given a NumPy array 'arr', check if its data type is float64.
#arr = np.array([1.5, 2.6, 3.7])
import numpy as np
arr = np.array([1.5, 2.6, 3.7])
is_float64 = arr.dtype == np.float64
print(is_float64)

True


In [7]:
# 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print(arr)
print(arr.dtype)

[1.+2.j 3.+4.j 5.+6.j]
complex128


In [8]:
# 4.Convert an existing NumPy array 'arr' of integers to float32
arr = np.array([1, 2, 3, 4, 5], dtype=np.int32)
arr_float32 = arr.astype(np.float32)
print(arr_float32)

[1. 2. 3. 4. 5.]


In [9]:
# 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
arr = np.array([1.5,2.5,3.5], dtype=np.float64)
arr_float32 = arr.astype(np.float32)
print(arr_float32)

[1.5 2.5 3.5]


In [10]:
# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data
#type.
def array_attributes(arr):
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    return shape, size, dtype
arr = np.array([[1,2,3],[4,5,6]])
array_attributes(arr)

((2, 3), 6, dtype('int64'))

In [13]:
# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.
def array_dimension(arr):
    dimensionality = arr.ndim
    return dimensionality

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
array_dimension(arr)

2

In [16]:
# 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
#size in bytes.
def item_size_info(arr):
    item_size = arr.itemsize
    total_size = arr.nbytes
    return item_size, total_size
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
item_size_info(arr)

(8, 72)

In [17]:
# 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
def array_strides(arr):
    strides = arr.strides
    return strides
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
array_strides(arr)

(24, 8)

In [18]:
# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape
#and strides of the array.
def shape_stride_relationship(arr):
    shape = arr.shape
    strides = arr.strides
    return shape, strides

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
shape_stride_relationship(arr)

((3, 3), (24, 8))

In [20]:
# 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
#zeros with `n` elements.
def create_zeros_array(n):
    zeros_array = np.zeros(n)
    return zeros_array
create_zeros_array(5)

array([0., 0., 0., 0., 0.])

In [21]:
# 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
#NumPy array filled with ones of size `rows x cols`.
def create_ones_matrix(rows, cols):
    ones_matrix = np.ones((rows, cols))
    return ones_matrix
create_ones_matrix(3,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
#13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
#creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
#`step`
def generate_range_array(start, stop, step):
    import numpy as np
    return np.arange(start, stop, step)
print(generate_range_array(2, 10, 2))

[2 4 6 8]


In [24]:
# 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
#arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
#(inclusive).
def generate_linear_space(start,stop,num):
  return np.linspace(start,stop,num)

generate_linear_space(1,10,5)


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [25]:
# 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
#identity matrix of size `n x n` using `numpy.eye`.
def create_identity_matrix(n):
    import numpy as np
    return np.eye(n)
create_identity_matrix(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
# 16. Write a function that takes a Python list and converts it into a NumPy array.
def python_list_to_numpy_array(lst):
    import numpy as np
    return np.array(lst)

python_list_to_numpy_array([1,2,3,4,5,6,7])


array([1, 2, 3, 4, 5, 6, 7])

In [28]:
#17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
#same data.
def create_view_array(arr):
  numpy_view = arr.view()
  return numpy_view

arr = np.array([1,2,3])
create_view_array(arr)

array([1, 2, 3])

In [32]:
# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.
def concatenate_arrays(arr1, arr2, axis):
    return np.concatenate((arr1, arr2), axis=axis)
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
axis = 0
concatenate_arrays(arr1,arr2,axis)

array([1, 2, 3, 4, 5, 6])

In [39]:
# 19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.
#concatenate`.
def horizontally_arrays(arr1, arr2):
  return np.concatenate((arr1,arr2))
arr2 = ([[1,2,3],[8,5,2]])
arr1 = ([[4,5,6],[7,8,9]])
horizontally_arrays(arr1,arr2)

array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [8, 5, 2]])

In [41]:
# 20. Write a function that vertically stacks multiple NumPy arrays given as a list.
def vertically_stacks(arrays):
  return np.vstack(arrays)
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.array([7,8,9])
arrays  = (arr1 , arr2, arr3)
vertically_stacks(arrays)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
#with a given step size.
def create_array(start, stop, step):
  array = np.arange(start,stop+1,step)
  return array
create_array(1,50,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [50]:
# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1
#(inclusive).
def lin_space():
  return np.linspace(0,1,10)
lin_space()

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [52]:
# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
# 1000 (inclusive).
def generate_log_space():
    return np.logspace(0, 1000, 5)
print(generate_log_space())



[1.e+000 1.e+250     inf     inf     inf]


/usr/local/lib/python3.10/dist-packages/numpy/core/function_base.py:298: RuntimeWarning: overflow encountered in power
  return _nx.power(base, y)


In [53]:
def generate_log_space():
    return np.logspace(0, 3, 5)
print(generate_log_space())

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [54]:
#24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
#are random integers between 1 and 100.
import pandas as pd
import numpy as np
arr=np.random.randint(1,100,(5,3))
df=pd.DataFrame(arr,columns=['A','B','C'])
print(df)

    A   B   C
0  57  18  80
1  73  81  74
2   6  82  30
3  61   1  80
4  28  86  54


In [55]:
#25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
#with zeros. Use NumPy operations within the Pandas DataFrame.
def replace_negatives_with_zero(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df
data = {'A': [1, -2, 3], 'B': [-4, 5, -6]}
df = pd.DataFrame(data)
print(replace_negatives_with_zero(df, 'A'))


   A  B
0  1 -4
1  0  5
2  3 -6


In [57]:
#26. Access the 3rd element from the given NumPy array.
arr = np.array([10,20,30,40,50])
arr[2]

30

In [62]:
# 27. Retrieve the element at index (1, 2) from the 2D NumPy array.
def get_element(arr):
  return arr[1,2]

arr_2d =np.array([[1,2,3],[4,5,6],[7,8,9]])
get_element(arr_2d)

6

In [63]:
# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
def extract_element(arr):
  return arr[arr>5]
arr = np.array([3, 8, 2, 10, 5, 7])
extract_element(arr)

array([ 8, 10,  7])

In [64]:
# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
def slicing_array(arr):
  return arr[2:6]
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
slicing_array(arr)

array([3, 4, 5, 6])

In [65]:
# 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
def extract_element(arr):
  return arr[0:2,1:3]
arr  =np.array([[1,2,3],[4,5,6],[7,8,9]])
extract_element(arr)

array([[2, 3],
       [5, 6]])

In [69]:
# 31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices
#provided in another array.
def extract_elements(arr, indices):
    return arr[indices[:,0], indices[:,1]]
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
indices = np.array([[0,1],[1,2],[2,0]])
extract_elements(arr,indices)

array([2, 6, 7])

In [70]:
# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using
#boolean indexing.
def filter_array(arr, threshold):
    return arr[arr > threshold]
arr = np.array([1,2,3,8,5,9,7])
threshold = 6
filter_array(arr,threshold)

array([8, 9, 7])

In [82]:
#33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
#separate arrays for each dimension.
def extract_elements(array, indices_x, indices_y, indices_z):

  extracted_elements = array[indices_x, indices_y, indices_z]
  return extracted_elements
array_3d = np.arange(27).reshape(3, 3, 3)
indices_x = np.array([0,1,2])
indices_y = np.array([1,2,0])
indices_z = np.array([2,0,1])
extracted_elements = extract_elements(array_3d, indices_x, indices_y, indices_z)
print(extracted_elements)

[ 5 15 19]


In [77]:
def extract_from_3d(arr, x_idx, y_idx, z_idx):
    return arr[x_idx, y_idx, z_idx]
arr_3d = np.arange(27).reshape(3, 3, 3)
x_idx = [0, 1, 2]
y_idx = [1, 2, 0]
z_idx = [2, 0, 1]
print(extract_from_3d(arr_3d, x_idx, y_idx, z_idx))

[ 5 15 19]


In [83]:
# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied
#using boolean indexing.
def return_elements_from_array(arr, condition1, condition2):
    result = arr[(arr > condition1) & (arr < condition2)]
    return result
arr  = np.array([[1,2,3,],[4,5,6]])
condition1 = 5
condition2 = 10
return_elements_from_array(arr, condition1, condition2)

array([6])

In [84]:
# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided
#in separate arrays.
def extract_elements(arr, row_indices, col_indices):
  return arr[row_indices,col_indices]
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
row_indices = np.array([0,1,2])
col_indices = np.array([0,1,2])
print(extract_elements(arr,row_indices,col_indices))

[1 5 9]


In [85]:
# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
def add_scalar_to_array(arr):
    scalar = 5
    result = arr + scalar
    return result
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
add_scalar_to_array(arr)

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [87]:
# 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
#corresponding element in arr1 using NumPy broadcasting
def multiply_rows(arr1,arr2):
  return arr2*arr1[:, np.newaxis]
arr1 = np.array([1,2,3])
arr2 = np.array([[1,2,3,4],[5,6,4,7],[8,9,6,4]])
multiply_rows(arr1,arr2)

array([[ 1,  2,  3,  4],
       [10, 12,  8, 14],
       [24, 27, 18, 12]])

In [95]:
#38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
#NumPy broadcasting.
def adding_row(arr1,arr2):
  return arr2+arr1[:,np.newaxis]
arr1 = np.array([1,2,3,4])
arr2 = np.array([[1,2,3],[5,4,6],[7,8,9],[8,5,2]])
adding_row(arr1,arr2)

array([[ 2,  3,  4],
       [ 7,  6,  8],
       [10, 11, 12],
       [12,  9,  6]])

In [93]:
#39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
#broadcasting.
def adding_row(arr1,arr2):
  return arr1+arr2#[:,np.newaxis]
arr1 = np.array([[1],[5],[9]])
arr2 = np.array([1,2,3])
adding_row(arr1,arr2)

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [100]:
# 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
#broadcasting. Handle the shape incompatibility.
def multiple_arr(arr,arr2):
  try:
        return arr * arr2
  except ValueError as e:
        return f"Shape mismatch: {e}"
arr = np.array([[1,2,3],[7,5,3]])
arr2 = np.array([[2,3],[4,5]])
multiple_arr(arr,arr2)

'Shape mismatch: operands could not be broadcast together with shapes (2,3) (2,2) '

In [101]:
# 41. Calculate column-wise mean for the given array
def cumulative_sum(arr):
    return np.cumsum(arr, axis=0)
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(cumulative_sum(arr))


[[1 2 3]
 [5 7 9]]


In [2]:
# 42. Find maximum value in each row of the given array
def max_value(arr):
    max_values = []
    for row in arr:
        max_value = max(row)
        max_values.append(max_value)
    return max_values

arr = [[1, 2, 3], [4, 5, 6]]
max_values = max_value(arr)
print(max_values)

[3, 6]


In [5]:
#43. For the given array, find indices of maximum value in each column
import numpy as np
def max_indices_per_column(arr):
  return np.argmax(arr, axis=0)
arr = np.array([[1,2,3],[4,5,6]])
print(max_indices_per_column(arr))

[1 1 1]


In [6]:
# 44.for the given array, apply custom function to calculate moving sum along rows
def moving_sum(arr,window_size=2):
  return np.array([np.convolve(row,np.ones(window_size,dtype=int),'valid')for row in arr])

arr = np.array([[1, 2, 3], [4, 5, 6]])
moving_sum(arr,window_size=2)

array([[ 3,  5],
       [ 9, 11]])

In [7]:
# 45. In the given array, check if all elements in each column are even.
def all_even_columns(arr):
    return np.all(arr % 2 == 0, axis=0)
arr = np.array([[2, 4, 6], [3, 5, 7]])
print(all_even_columns(arr))


[False False False]


In [8]:
#46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
#reshaped matrix.
def reshape_array(arr, m, n):
    return arr.reshape(m, n)
arr = np.array([1, 2, 3, 4, 5, 6])
print(reshape_array(arr, 2, 3))


[[1 2 3]
 [4 5 6]]


In [9]:
#47. Create a function that takes a matrix as input and returns the flattened array.
def flatten_matrix(matrix):
    return matrix.flatten()
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(flatten_matrix(matrix))


[1 2 3 4 5 6]


In [10]:
#48. Write a function that concatenates two given arrays along a specified axis.
def concatenate_arrays(arr1, arr2, axis):
    return np.concatenate((arr1, arr2), axis=axis)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(concatenate_arrays(arr1, arr2, axis=0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [11]:
# 49. Split an array into multiple sub-arrays along a specified axis.
def split_array(arr, indices_or_sections, axis=0):
    return np.array_split(arr, indices_or_sections, axis=axis)
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(split_array(arr, 2, axis=1))


[array([[1, 2],
       [4, 5]]), array([[3],
       [6]])]


In [12]:
# 50. Write a function that inserts and then deletes elements from a given array at specified indices.
def insert_and_delete(arr, insert_indices, values, delete_indices):
    arr = np.insert(arr, insert_indices, values)
    arr = np.delete(arr, delete_indices)
    return arr
arr = np.array([1, 2, 3, 4])
print(insert_and_delete(arr, [2], [99], [0]))  # Output: [2 99 3 4]


[ 2 99  3  4]


In [15]:
# 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
#Perform element-wise addition between `arr1` and `arr2`
arr1 = np.random.randint(0, 10, 5)
arr2 = np.arange(1, 11)[:5]
print(arr1)
print(arr2)
print(arr1 + arr2)


[0 9 7 8 6]
[1 2 3 4 5]
[ 1 11 10 12 11]


In [16]:
#52. Element-wise subtraction between two arrays.
arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
print(arr1)
print(arr2)
print(arr1 - arr2)


[10  9  8  7  6  5  4  3  2  1]
[ 1  2  3  4  5  6  7  8  9 10]
[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [17]:
# 53. Perform element-wise multiplication between two arrays.
arr1 = np.random.randint(0, 10, 5)
arr2 = np.arange(1, 6)
print(arr1 * arr2)


[ 7  6  0 20 20]


In [18]:
# 54. Perform element-wise division between two arrays.
arr1 = np.arange(2, 12, 2)
arr2 = np.arange(1, 6)
print(arr1 / arr2)


[2. 2. 2. 2. 2.]


In [19]:
#55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
#reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.
arr1 = np.arange(1, 6)
arr2 = arr1[::-1]
print(arr1 ** arr2)



[ 1 16 27 16  5]


In [20]:
# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
def count_substring(arr, substring):
    return np.char.count(arr, substring)
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
print(count_substring(arr, 'hello'))


[1 0 1 0 1]


In [21]:
# 57. Write a function that extracts uppercase characters from a NumPy array of strings.
#arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
def extract_uppercase(arr):
    return np.array([''.join([char for char in word if char.isupper()]) for word in arr])
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
print(extract_uppercase(arr))


['H' 'W' 'OAI' 'GPT']


In [22]:
# 58. Replace occurrences of a substring in a NumPy array of strings.
def replace_substring(arr, old, new):
    return np.char.replace(arr, old, new)
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print(replace_substring(arr, 'apple', 'fruit'))


['fruit' 'banana' 'grape' 'pinefruit']


In [24]:
# 59. Write a function that concatenates strings in a NumPy array element-wise
def concatenate_strings(arr, suffix):
    return np.char.add(arr, suffix)
arr = np.array(['apple', 'banana', 'grape'])
print(concatenate_strings(arr, 's'))


['apples' 'bananas' 'grapes']


In [25]:
#60. Write a function that finds the length of the longest string in a NumPy array.

#arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

def longest_string_length(arr):
    return max(len(s) for s in arr)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print(longest_string_length(arr))


9


In [28]:
#61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
#standard deviation of the dataset using NumPy's functions.

data = np.random.randint(1, 1001, 100)
mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_dev = np.std(data)

print(f"Mean: {mean}, Median: {median}, Variance: {variance}, Std Dev: {std_dev}")


Mean: 527.13, Median: 523.0, Variance: 77344.5931, Std Dev: 278.1089590430341


In [26]:
#62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
#dataset

data = np.random.randint(1, 101, 50)
percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)

print(f"25th Percentile: {percentile_25}, 75th Percentile: {percentile_75}")


25th Percentile: 26.25, 75th Percentile: 62.75


In [27]:
#63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these
#arrays using NumPy's `corrcoef` function.

arr1 = np.random.randint(1, 101, 50)
arr2 = np.random.randint(1, 101, 50)
correlation = np.corrcoef(arr1, arr2)

print("Correlation Coefficient Matrix:\n", correlation)


Correlation Coefficient Matrix:
 [[1.         0.05452034]
 [0.05452034 1.        ]]


In [29]:
#64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.
matrix1 = np.random.randint(1, 10, (3, 3))
matrix2 = np.random.randint(1, 10, (3, 3))
result = np.dot(matrix1, matrix2)

print("Matrix Multiplication Result:\n", result)


Matrix Multiplication Result:
 [[ 91  41  57]
 [112  56  40]
 [ 98  52  46]]


In [30]:
#65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
#percentiles along with the first and third quartiles.

data = np.random.randint(10, 1001, 50)
percentile_10 = np.percentile(data, 10)
percentile_50 = np.percentile(data, 50)
percentile_90 = np.percentile(data, 90)
q1 = np.percentile(data, 25)
q3 = np.percentile(data, 75)

print(f"10th: {percentile_10}, Median: {percentile_50}, 90th: {percentile_90}, Q1: {q1}, Q3: {q3}")


10th: 128.70000000000002, Median: 543.5, 90th: 860.3, Q1: 344.5, Q3: 757.25


In [31]:
#66. Create a NumPy array of integers and find the index of a specific element.
arr = np.array([10, 20, 30, 40, 50])
element = 30
index = np.where(arr == element)[0]

print(f"Index of {element}: {index}")


Index of 30: [2]


In [32]:
#67. Generate a random NumPy array and sort it in ascending order.
arr = np.random.randint(1, 100, 10)
sorted_arr = np.sort(arr)

print(f"Original: {arr}, Sorted: {sorted_arr}")


Original: [15 36 16 40 17 90 14 29 89  6], Sorted: [ 6 14 15 16 17 29 36 40 89 90]


In [33]:
#68. Filter elements >20 in the given NumPy array.
arr = np.array([12, 25, 6, 42, 8, 30])
filtered = arr[arr > 20]

print("Filtered Elements > 20:", filtered)


Filtered Elements > 20: [25 42 30]


In [34]:
# 69. Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])
filtered = arr[arr % 3 == 0]

print("Elements divisible by 3:", filtered)


Elements divisible by 3: [12 15]


In [35]:
# 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array
arr = np.array([10, 20, 30, 40, 50])
filtered = arr[(arr >= 20) & (arr <= 40)]

print("Elements ≥20 and ≤40:", filtered)


Elements ≥20 and ≤40: [20 30 40]


In [37]:
#71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.

arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder

print("Byte Order:", byte_order)  # Output: '=' for native, '<' for little-endian, '>' for big-endian


Byte Order: =


In [38]:
# 72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
arr = np.array([1, 256, 65536], dtype='>i4')  # Big-endian integer array
arr.byteswap(inplace=True)
print(arr)  # Swapped to little-endian


[16777216    65536      256]


In [39]:
#73. For the given NumPy array, swap its byte order without modifying the original array using
#`newbyteorder()`.

arr = np.array([1, 256, 65536], dtype='>i4')  # Big-endian integer array
swapped_arr = arr.newbyteorder()
print(swapped_arr)  # Little-endian
print(arr)  # Original remains unchanged


[16777216    65536      256]
[    1   256 65536]


In [40]:
#74. For the given NumPy array and swap its byte order conditionally based on system endianness using
#`newbyteorder()`.

arr = np.array([1, 256, 65536], dtype='>i4')  # Big-endian integer array
if arr.dtype.byteorder != '=':  # Check if native byte order
    arr = arr.newbyteorder()
print(arr)


[16777216    65536      256]


In [41]:
#75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`
#attribute `byteorder

arr = np.array([1, 2, 3], dtype='>i4')  # Big-endian integer array
if arr.dtype.byteorder != '=':  # Not native byte order
    print("Byte swapping is necessary.")
else:
    print("Byte swapping is not necessary.")


Byte swapping is necessary.


In [42]:
#76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
#an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.
arr1 = np.arange(1, 11)
copy_arr = arr1.copy()
copy_arr[0] = 99
print("Original array:", arr1)
print("Modified copy:", copy_arr)


Original array: [ 1  2  3  4  5  6  7  8  9 10]
Modified copy: [99  2  3  4  5  6  7  8  9 10]


In [43]:
#77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
#the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`

matrix = np.random.randint(1, 10, (3, 3))
view_slice = matrix[1:, :2]
view_slice[0, 0] = 99
print("Original matrix:\n", matrix)
print("Modified slice:\n", view_slice)


Original matrix:
 [[ 5  7  9]
 [99  6  5]
 [ 3  5  8]]
Modified slice:
 [[99  6]
 [ 3  5]]


In [44]:
#78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
#`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`

array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[:, :2]
view_b += 5
print("Original array:\n", array_a)


Original array:
 [[ 6  7  3]
 [ 9 10  6]
 [12 13  9]
 [15 16 12]]


In [45]:
#79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
#`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
#reflects changes in the original `orig_array`.


orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)
reshaped_view[0, 0] = 99
print("Original array:\n", orig_array)
print("Reshaped view:\n", reshaped_view)


Original array:
 [[99  2  3  4]
 [ 5  6  7  8]]
Reshaped view:
 [[99  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]


In [46]:
#80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
#elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

data = np.random.randint(1, 10, (3, 4))
data_copy = data[data > 5].copy()
data_copy[0] = 99
print("Original array:\n", data)
print("Modified copy:", data_copy)


Original array:
 [[9 6 7 6]
 [5 1 5 6]
 [9 6 6 1]]
Modified copy: [99  6  7  6  6  9  6  6]


In [47]:
#81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction
#operations between them.

A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))
add_result = A + B
sub_result = A - B
print("Addition:\n", add_result)
print("Subtraction:\n", sub_result)


Addition:
 [[16  8 11]
 [12 11  7]
 [17 13 10]]
Subtraction:
 [[-2  6 -1]
 [ 4  5 -5]
 [-1 -1  6]]


In [48]:
#82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.
C = np.random.randint(1, 10, (3, 2))
D = np.random.randint(1, 10, (2, 4))
result = np.dot(C, D)
print("Matrix Multiplication Result:\n", result)


Matrix Multiplication Result:
 [[135  84  81  81]
 [135  66  69  84]
 [126  58  62  79]]


In [49]:
#83. Create a matrix `E` and find its transpose
E = np.random.randint(1, 10, (3, 3))
transpose = E.T
print("Original Matrix:\n", E)
print("Transpose:\n", transpose)


Original Matrix:
 [[1 3 4]
 [3 8 9]
 [4 6 3]]
Transpose:
 [[1 3 4]
 [3 8 6]
 [4 9 3]]


In [50]:
#84. Generate a square matrix `F` and compute its determinant
F = np.random.randint(1, 10, (3, 3))
determinant = np.linalg.det(F)
print("Matrix:\n", F)
print("Determinant:", determinant)


Matrix:
 [[2 9 2]
 [3 2 5]
 [2 9 3]]
Determinant: -23.0


In [51]:
#85. Create a square matrix `G` and find its inverse
G = np.random.randint(1, 10, (3, 3))
if np.linalg.det(G) != 0:  # Check if the matrix is invertible
    inverse = np.linalg.inv(G)
    print("Matrix:\n", G)
    print("Inverse:\n", inverse)
else:
    print("Matrix is not invertible.")


Matrix:
 [[4 6 5]
 [7 2 7]
 [9 3 6]]
Inverse:
 [[-0.08571429 -0.2         0.3047619 ]
 [ 0.2        -0.2         0.06666667]
 [ 0.02857143  0.4        -0.32380952]]
